#This is my first action
name: UAT
env:
  BatchVersion: JavaSE_Batch3
on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  MyFirstJobs:
    runs-on: ubuntu-latest
    env:
      Days: All-Days
    steps:
      - run: echo "Hello World";
      - name: Update package
        run: sudo apt-get update
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List file in repository
        env:
          my-steps: First-Step
        run: | 
              echo "Variable from Secrity Var : ${{vars.FILE_TO_CHECK}}"
              echo "Now ${{env.BatchVersion}} Example Date: ${{env.Days}} Steps: ${{env.my-steps}}"
              echo "Input log level ${{inputs.logLevel}}"
              echo "The repository ${{github.repository}} contains the following file" 
              tree
