name: My First Action
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  MyFirstJobs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World";
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List file in repository
        run: | 
              echo "The repository ${{github.repository}} contains the following file" 
              tree
