#This is my first action
name: My First Action
on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  MyFirstJobs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World";
      - name: Update package
        run: sudo apt-get update
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List file in repository
        run: | 
              echo "Input log level ${{inputs.logLevel}}"
              echo "The repository ${{github.repository}} contains the following file" 
              tree
